#!/usr/bin/env bash

# Debug
# set -x

# Fail fast
set -e

./manage.py test

coverage run --source=dothis,volunteering manage.py harvest "$@" --port=8081
coverage report
coverage annotate

echo
echo "Unused steps"
echo "------------"
find . -name "*steps.py,cover" | xargs grep -n -H -B2 '^!' | sed 's/,cover[-:]/:/'

echo
echo "Unused helpers"
echo "------------"
find . -name "*helpers*,cover" | xargs grep -n -H -B1 '^!' | sed 's/,cover[-:]/:/'
